language: python
cache:
  pip: true
  directories:
    - models/
python:
  - "3.7"
install:
  - pip install -r requirements_dev.txt
  - bash getmodels.sh
script:
  - coverage run --rcfile=.coveragerc manage.py test
after_success:
  - codecov