language: python
services:
  - postgresql
cache:
  pip: true
  directories:
    - $HOME/.cache/pip
    - storage/data/models/
python:
  - "3.7"
install:
  - pip install -r requirements_dev.txt
  - bash getmodels.sh
env:
  global:
    - DJANGO_SETTINGS_MODULE=dnfas.settings.testing
    - PGUSER=postgres
    - PGPASSWORD=''
before_script:
  - bash dbinit.sh
script:
  - coverage run --rcfile=.coveragerc manage.py test --keepdb
after_success:
  - codecov