language: python
services:
  - postgresql
cache:
  pip: true
  directories:
    - models/
python:
  - "3.7"
install:
  - pip install -r requirements_dev.txt
  - bash getmodels.sh
env:
  - DJANGO_SETTINGS_MODULE=dnfas.settings.testing
  - PGUSER=postgres
  - PGPASSWORD=''
script:
  - bash test.sh
after_success:
  - codecov