# Generated by Django 2.2.8 on 2020-01-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='detection_min_size',
            new_name='detection_min_height',
        ),
        migrations.AddField(
            model_name='task',
            name='detection_min_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='frontal_faces',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
