# Generated by Django 3.0.2 on 2020-01-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face',
            name='size_bytes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
