# Generated by Django 3.0.2 on 2020-01-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfapi', '0002_auto_20200106_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectsegment',
            name='disk_cached',
            field=models.BooleanField(blank=True, default=False, help_text='Indicates if linked train data if stored in disk.'),
        ),
        migrations.AlterField(
            model_name='subjectsegment',
            name='max_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subjectsegment',
            name='min_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subjectsegment',
            name='title',
            field=models.CharField(blank=True, help_text='The segment title.', max_length=255),
        ),
    ]
