# Generated by Django 3.0.2 on 2020-02-25 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dfapi', '0004_auto_20200217_1224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recognition',
            old_name='similarity_threshold',
            new_name='sim_thres',
        ),
    ]
