# Generated by Django 3.0.2 on 2020-02-25 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dfapi', '0005_auto_20200225_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recognition',
            old_name='sim_thres',
            new_name='sim_thresh',
        ),
    ]
