# Generated by Django 3.0.2 on 2020-02-27 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfapi', '0006_auto_20200225_1421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recognition',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='recognition',
            name='filter',
        ),
        migrations.RemoveField(
            model_name='task',
            name='repeat',
        ),
        migrations.AlterField(
            model_name='task',
            name='repeat_days',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
    ]
