# Generated by Django 3.0.2 on 2020-02-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfapi', '0007_auto_20200227_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorecord',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
