# Generated by Django 3.0.2 on 2020-03-01 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dfapi', '0008_videorecord_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='unique_id',
        ),
    ]
