# Generated by Django 3.0.2 on 2020-03-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfapi', '0009_remove_subject_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='sex',
            field=models.CharField(blank=True, choices=[('man', 'man'), ('woman', 'woman')], default='', max_length=16),
        ),
    ]
