# Generated by Django 3.0.2 on 2020-03-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfapi', '0011_auto_20200312_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='pred_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='pred_sex',
            field=models.CharField(blank=True, choices=[('man', 'man'), ('woman', 'woman')], default='', max_length=16),
        ),
    ]
