# Generated by Django 3.0.2 on 2020-03-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfapi', '0013_auto_20200319_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('model', models.CharField(choices=[('task', 'task'), ('camera', 'task'), ('video', 'video')], max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='TaskTag',
        ),
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(related_name='tasks', to='dfapi.Tag'),
        ),
    ]
