# Generated by Django 3.0.2 on 2020-03-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfapi', '0014_auto_20200320_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='pred_age_var',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='face',
            name='pred_sex_score',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
