# Generated by Django 3.0.2 on 2020-03-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfapi', '0015_auto_20200323_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='pred_age_var',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='subject',
            name='pred_sex_score',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
